server:
  port: 8081
# server.port=8086
spring.application.name: application-catalog
# data will be streamed to get exposed on the hystrix dashboard
spring:
  cloud:
    config:
      enabled: true
  config:
    import: configserver:http://localhost:8888


